matrix:
  include:
    - language: node_js
      node_js:
        - "9.5"
        - "8"
      before_install:
        - cd nodejs
      install:
        - npm install
      script:
        - npm run test  
      cache:
        directories:
          - "node_modules"
notifications:
  email:
    on_failure: always
    on_success: change

